<a href="https://colab.research.google.com/github/richard-ky/desynchronization/blob/main/Models.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Data Preprocessing

In [ ]:
# Mount drive for quick access to files

from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
# Import data

import scipy

temp = scipy.io.loadmat('/content/drive/MyDrive/Data Collection Neural Network Synchronization/Desynchronization/Data/DesyncneuraldataTrial_1(10,0.1,0.1,10,5,450).mat')

In [ ]:
import pandas as pd

In [ ]:
# Create new DataFrame

df = pd.DataFrame()

In [ ]:
# Check shape

print(temp['Input_data'].shape)
print(temp['Label_data'].shape)
print(temp['spike_time_input'].shape)
print(temp['spike_time_label'].shape)

(1608, 1)
(1601, 1)
(500, 1600)
(500, 1600)

In [ ]:
# Add data to DataFrame

df['input'] = temp['Input_data'][8:, 0]
df['label'] = temp['Label_data'][1:, 0]
df.head()

   input  label
0   20.0   40.0
1   40.0   40.0
2   40.0   40.0
3   40.0   40.0
4   40.0   40.0

In [ ]:
# Create a row of all the non-lambda features 

new = pd.DataFrame(temp['Input_data'][2:8, 0]).transpose()
new

      0    1    2     3    4         5
0  10.0  0.1  0.1  10.0  5.0  0.706738

In [ ]:
# Create the column names

new.columns = ['Amp', 'PW1', 'PW2', 'PW3', 'Ns', 'Re1']
new

    Amp  PW1  PW2   PW3   Ns       Re1
0  10.0  0.1  0.1  10.0  5.0  0.706738

In [ ]:
# Duplicate the row

new = pd.concat([new]*1600, ignore_index=True)
new.head()

    Amp  PW1  PW2   PW3   Ns       Re1
0  10.0  0.1  0.1  10.0  5.0  0.706738
1  10.0  0.1  0.1  10.0  5.0  0.706738
2  10.0  0.1  0.1  10.0  5.0  0.706738
3  10.0  0.1  0.1  10.0  5.0  0.706738
4  10.0  0.1  0.1  10.0  5.0  0.706738

In [ ]:
# Add non-lambda features to DataFrame

df[['Amp', 'PW1', 'PW2', 'PW3', 'Ns', 'Re1']] = new[['Amp', 'PW1', 'PW2', 'PW3', 'Ns', 'Re1']]

In [ ]:
# Rearrange columns so 'label' is last

df = df[['input', 'Amp', 'PW1', 'PW2', 'PW3', 'Ns', 'Re1', 'label']]
df.head()

   input   Amp  PW1  PW2   PW3   Ns       Re1  label
0   20.0  10.0  0.1  0.1  10.0  5.0  0.706738   40.0
1   40.0  10.0  0.1  0.1  10.0  5.0  0.706738   40.0
2   40.0  10.0  0.1  0.1  10.0  5.0  0.706738   40.0
3   40.0  10.0  0.1  0.1  10.0  5.0  0.706738   40.0
4   40.0  10.0  0.1  0.1  10.0  5.0  0.706738   40.0

In [ ]:
# Check counts

print(df['label'].unique())
print(df['label'].value_counts())

[40. 20. 60.]
40.0    1194
20.0     380
60.0      26
Name: label, dtype: int64

#Models

In [ ]:
# Split data into train and test sets

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df[['input', 'Amp', 'PW1', 'PW2', 'PW3', 'Ns', 'Re1']], df['label'], test_size=.2)

In [ ]:
# Support vector classifier

from sklearn.svm import SVC
from sklearn import metrics

svm_classifier = SVC()
svm_classifier.fit(X_train, y_train)

pred = svm_classifier.predict(X_test)
print('Accuracy: ', metrics.accuracy_score(y_test, pred))

Accuracy:  0.696875